### ISSUE TITLE
ヒット件数の修正

### ISSUE THREAD

**Issue by inutano** [dogrunjp/DDBJSearch#22]
検索時のヒット件数が実際にSolrの検索でヒットする件数と異なっている。おそらく、ページングのために部分的に取得した件数が表示されている。Solrに総ヒット件数を問い合わせるクエリを先に実行し、そこから実際の件数を取得、表示するように修正。

"Search Results for term: human, XXX SRA entries" と表示されているところを "XXX SRA studies found. Search query: human" に変更。

**Comment by dogrunjp** [comment]
修正しました。
